version: '3.9'
services:
  locations-app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    # restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
